### ISSUE TITLE
issue with compiling virtualbox modules

### ISSUE THREAD

**Issue by hphilm** [philmmanjaro/project-sx#2]
We get following error:

```
In file included from ./include/linux/atomic.h:4:0,
                 from ./include/linux/jump_label.h:183,
                 from ./arch/x86/include/asm/string_64.h:5,
                 from ./arch/x86/include/asm/string.h:4,
                 from ./include/linux/string.h:18,
                 from /var/lib/dkms/vboxguest/5.1.22_OSE/build/vboxvideo/include/iprt/string.h:37,
                 from /var/lib/dkms/vboxguest/5.1.22_OSE/build/vboxvideo/HGSMICommon.c:21:
./arch/x86/include/asm/atomic.h: In function 'atomic_try_cmpxchg':
./arch/x86/include/asm/atomic.h:192:2: error: undefined named operand 'new'
  return try_cmpxchg(&v->counter, old, new);
  ^~~~~~
./arch/x86/include/asm/atomic.h:192:2: error: undefined named operand 'new'
./arch/x86/include/asm/atomic.h:192:2: error: undefined named operand 'new'
./arch/x86/include/asm/atomic.h:192:2: error: undefined named operand 'new'
```
This got introduced with https://github.com/torvalds/linux/commit/a9ebf306f52c756c4f9e50ee9a60cd6389d71344.

**Comment by hphilm** [comment]
Issue seems to be [known](http://mom.hlmjr.com/2017/05/28/bleeding-on-the-edge-app-emulationvirtualbox-modules-5-1-22-vs-kernel-4-12-0-rc2/) and should be fixed with **v5.1.23**. Might be a new issue with updated **toolchain**.

**Comment by oberon-manjaro** [comment]
We will see. In any case the guy had the same error message. although it seems he was using regular linux412, so not sure if the issue might be created by one of our patches...

**Comment by hphilm** [comment]
The change was introduced on the regular source: https://github.com/torvalds/linux/commit/a9ebf306f52c756c4f9e50ee9a60cd6389d71344 I checked the Intel-Patch-Set and couldn't find anything there causing that issue.

**Comment by oberon-manjaro** [comment]
Solved with **virtualbox 5.1.24** 👍
